const CSV="https://raw.githubusercontent.com/Santhorn/DVT_Interactive_Data_Visualization_FINAL/main/data/cleaned/_2568_cleaned.csv",months=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"],weekdays=["จันทร์","อังคาร","พุธ","พฤหัสบดี","ศุกร์","เสาร์","อาทิตย์"];let data=[],charts={};
function parseDate(x){const d=new Date(x);return d}
function prep(d){d.Age=+d.Age;d.date=parseDate(d["Dead Date"]);d.month=months[d.date.getMonth()];d.weekday=weekdays[(d.date.getDay()+6)%7];return d}
function fill(id,vals){const s=document.getElementById(id);s.innerHTML='<option value="ทั้งหมด">ทั้งหมด</option>';vals.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;s.appendChild(o)});s.onchange=update}
function count(arr,key){const m={};arr.forEach(d=>{const v=d[key]??"ไม่ระบุ";m[v]=(m[v]||0)+1});return Object.entries(m).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function filtered(){const m=document.getElementById("month").value,s=document.getElementById("sex").value,p=document.getElementById("province").value,v=document.getElementById("vehicle").value;return data.filter(d=>(m==="ทั้งหมด"||d.month===m)&&(s==="ทั้งหมด"||d.Sex===s)&&(p==="ทั้งหมด"||d["จ.ที่เสียชีวิต"]===p)&&(v==="ทั้งหมด"||d["Vehicle Merge Final"]===v))}
function destroy(){Object.values(charts).forEach(c=>c.destroy());charts={}}
function baseOpts(){return {responsive:true,maintainAspectRatio:false,plugins:{tooltip:{enabled:true},legend:{display:true}},animation:{duration:250}}}
function make(type,id,labels,vals,opts={}){charts[id]=new Chart(document.getElementById(id),{type,data:{labels,datasets:[{label:"จำนวนผู้เสียชีวิต",data:vals}]},options:{...baseOpts(),...opts}})}
function update(){const arr=filtered();document.getElementById("total").textContent=arr.length.toLocaleString();const ages=arr.map(d=>d.Age).filter(Number.isFinite);document.getElementById("avgAge").textContent=ages.length?(ages.reduce((a,b)=>a+b,0)/ages.length).toFixed(1):"-";const p=count(arr,"จ.ที่เสียชีวิต")[0],v=count(arr,"Vehicle Merge Final")[0];document.getElementById("topProvince").textContent=p?.label||"-";document.getElementById("topVehicle").textContent=v?.label||"-";destroy();
const mc=Object.fromEntries(months.map(x=>[x,0]));arr.forEach(d=>mc[d.month]++);make("line","line",months,months.map(x=>mc[x]),{scales:{y:{beginAtZero:true}}});
const sx=count(arr,"Sex");make("doughnut","donut",sx.map(x=>x.label),sx.map(x=>x.value),{plugins:{legend:{position:"bottom"}}});
const vh=count(arr,"Vehicle Merge Final").slice(0,12);make("bar","vehicleChart",vh.map(x=>x.label),vh.map(x=>x.value),{plugins:{legend:{display:false}},scales:{x:{ticks:{maxRotation:45,minRotation:25}}}});
const wd=weekdays.map(x=>({label:x,value:arr.filter(d=>d.weekday===x).length}));make("bar","weekday",wd.map(x=>x.label),wd.map(x=>x.value),{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}});
const pr=count(arr,"จ.ที่เสียชีวิต").slice(0,10).reverse();make("bar","provinceChart",pr.map(x=>x.label),pr.map(x=>x.value),{indexAxis:"y",plugins:{legend:{display:false}},scales:{x:{beginAtZero:true}}});
document.getElementById("summary").innerHTML=`ข้อมูลที่เลือกมี <b>${arr.length.toLocaleString()}</b> ราย อายุเฉลี่ย <b>${ages.length?(ages.reduce((a,b)=>a+b,0)/ages.length).toFixed(1):"-"}</b> ปี จังหวัดที่พบมากที่สุดคือ <b>${p?.label||"-"}</b> และยานพาหนะที่พบมากที่สุดคือ <b>${v?.label||"-"}</b>`;
}
document.getElementById("reset").onclick=()=>{["month","sex","province","vehicle"].forEach(id=>document.getElementById(id).value="ทั้งหมด");update()};
Papa.parse(CSV,{download:true,header:true,skipEmptyLines:true,complete:r=>{data=r.data.map(prep);fill("month",months);fill("sex",[...new Set(data.map(d=>d.Sex))].sort((a,b)=>a.localeCompare(b,"th")));fill("province",[...new Set(data.map(d=>d["จ.ที่เสียชีวิต"]))].sort((a,b)=>a.localeCompare(b,"th")));fill("vehicle",[...new Set(data.map(d=>d["Vehicle Merge Final"]))].sort((a,b)=>a.localeCompare(b,"th")));update()},error:e=>document.getElementById("summary").textContent="โหลดข้อมูลไม่สำเร็จ: "+e.message});
